- src/pages/MyPage/MyPayPage.tsx
- src/pages/MyPage/MyReviewPage.tsx
- src/pages/MyPage/components/CardHeader.tsx
- src/pages/MyPage/components/PossiblepayAmount.tsx
- src/pages/MyPage/components/ReviewCard.tsx
- src/pages/MyPage/components/ReviewTabs.tsx
- src/pages/MyPage/components/SalesHistoryCard.tsx
- close #22 
마이페이지-정산/리뷰 관리 페이지 구현 하였습니다!
정산/리뷰 페이지 UI 구현
https://github.com/user-attachments/assets/a61c493c-9f54-4b75-87fa-c79d91091b78
> [Feat] 정산관리, 리뷰관리 UI

- src/assets/icon-arrow-left-blue.svg
- src/assets/icon-rightArrow.svg
- src/components/Button/PrimaryButton.tsx
- src/pages/MyPage/MyInfoPage.tsx
- src/pages/MyPage/MyPayPage.tsx
- src/pages/MyPage/MyPaymentHistoryPage.tsx
- src/pages/MyPage/MyReviewPage.tsx
- src/pages/MyPage/components/InfoRow.tsx
- src/pages/MyPage/components/PaymentHistoryRow.tsx
- src/pages/MyPage/components/ReviewCard.tsx
- src/pages/MyPage/components/ReviewTabs.tsx
- src/pages/MyPage/components/singleModal.tsx
- src/routes/pageRoutes.tsx
- src/routes/routes.tsx
- close #18 
회원정보 페이지 UI 구현
회원정보 페이지속 "내역보기" 버튼 클릭시 보여지는 결제내역 페이지 UI구현
https://github.com/user-attachments/assets/f0fe91d4-0d90-4975-9fb2-bd0d3b921701
> [Feat] 회원정보/결제내역 페이지 UI

- src/pages/MainPage/components/filterBar.tsx
Fix:필터바 타입 오류
- close #26
필터 바 타입 오류 수정했습니다
혹시 배포 과정에서 다시 타입 오류 생기면 연락 부탁드립니다!
> 🐛 Fix:필터바 타입 오류 수정

- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/SearchPage.tsx
- src/pages/MainPage/components/SearchPrompter.tsx
- src/pages/MainPage/components/filterBar.tsx
- src/pages/MainPage/components/promptCard.tsx
- src/types/prompt.ts
> [fix] 검색페이지 오류 수정

- src/pages/MainPage/components/FilterDropdown.tsx
- src/pages/MainPage/components/MobileFilterModal.tsx
- src/pages/MainPage/components/MobilePrompt.tsx
- src/pages/MainPage/components/MobilePrompter.tsx
- src/pages/MainPage/components/filterBar.tsx
- close #81 
모바일 반응형 UI 수정 및 필터 기능 수정
> [Design]메인페이지 반응형 UI

- src/pages/MyPage/components/MessagePagination.tsx
- src/pages/MyPage/components/NotificationPagination.tsx
- src/pages/PromptCreatePage/PromptCreatePage.tsx
- src/pages/PromptCreatePage/components/ImageList.tsx
- src/pages/PromptCreatePage/components/MobileUploadModal.tsx
- src/pages/PromptCreatePage/components/UploadModal.tsx
- src/pages/PromptGuidePage/PromptGuidePage.tsx
- src/pages/PromptGuidePage/components/MobileList.tsx
- close #97 
QA 요청사항에 따라 페이지 UI 수정
- TIP, 공지사항 페이지
- 마이페이지 메시지함, 알림함 페이지
- 업로드 세부 설정 모달 & 프롬프트 작성 페이지
1. TIP, 공지사항 페이지에서 로그인 하지 않은 상태로 접속시 로그인 모달이 뜨게 해달라는 요청이 있었는데, 이 부분은 로그인 API 완료 이후에 제가 추가하겠습니다.
2. 현재 모바일 환경에서 어떠한 경우에, TabBar에 업로드 세부 설정 모달이 가려지는 문제가 있는 것으로 보입니다. 우선 제 쪽에서 재현이 안 되는 관계로 z-index를 수정했습니다만... 이후에 동일한 문제가 발생하는지 다시 확인해봐야 할 것 같습니다. 
> [Fix] 프롬프트 TIP, 프롬프트 작성하기 UI 수정

- package.json
- pnpm-lock.yaml
- src/pages/PromptDetailPage/PromptDetailPage.tsx
- src/pages/PromptDetailPage/components/PromptActions.tsx
- src/pages/PromptDetailPage/components/ReviewList.tsx
- src/pages/PromptDetailPage/components/UpdateModal.tsx
> [Design] qa 프롬프트 상세페이지 수정

- src/apis/axios.ts
JSON.parse로 가져오도록
- close #74 
- `axiosInstance`에서 `headers`에 토큰 가져오는 과정에서 `JSON.parse`가 생략되어 오류가 발생하는 문제를 해결했습니다.
> [Fix] axiosInstance 수정

- src/pages/PromptCreatePage/PromptCreatePage.tsx
프롬프트 업로드 페이지 API 연동 완료 (업로드 세부 설정 모달 포함)
- close #110 
프롬프트 업로드 (create) 페이지의 API 연동을 완료했습니다.
현재 이미지 업로드 관련해서, 이미지 URL 생성 이후 생성된 URL로 PUT 요청시 localhost 상에서는 CORS 오류가 발생합니다. 
따라서 서버에 올라간 뒤에야 이 기능이 동작하는지 여부를 확인할 수 있을 것 같습니다. (...) 
> [Feat] : 프롬프트 업로드 페이지 API 연동 완료 

- src/context/AuthContext.tsx
- src/pages/MyPage/MyPromptPage.tsx
> [Fix] 전역변수 user 타입 변경(#92)

- src/apis/MyPage/prompt.ts
- src/components/Modal/LoginSwitchModal.tsx
- src/context/AuthContext.tsx
- src/pages/MyPage/MyInfoPage.tsx
- src/pages/MyPage/components/InfoRow.tsx
- close #92 
마이페이지 부분 api 코드 구현 완료하였습니다
출금 요청 부분은 내일 모각작에서 민주님과 이야기 후 구현 예정입니다!
> [Feat] 마이페이지 api 구현

- src/components/Modal/LoginSwitchModal.tsx
- src/components/Modal/SocialLoginModal.tsx
- src/pages/MyPage/MyInfoPage.tsx
- src/pages/MyPage/MyPromptPage.tsx
- src/pages/MyPage/components/AccountEditForm.tsx
- src/pages/MyPage/components/Dropdown.tsx
- src/pages/MyPage/components/PromptCard.tsx
- close #92 
UI수정을 원래 125번 브랜치에서 했었어야 하는데 92번에서 해버려서 중간에 끊고 pr 올립니다.. 이후 UI관련 작업은 125번 브랜치에서 할 것 같습니다!
> [Feat]. 마이페이지 UI 수정

- src/apis/MyPage/account.ts
- src/apis/MyPage/pay.ts
- src/components/Modal/LoginSwitchModal.tsx
- src/components/Modal/SocialLoginModal.tsx
- src/hooks/mutations/MyPage/account.ts
- src/hooks/queries/MyPage/useGetAccount.ts
- src/pages/MyPage/MyPayPage.tsx
- src/pages/MyPage/MyPaymentHistoryPage.tsx
- src/pages/MyPage/components/AccountEditForm.tsx
- src/pages/MyPage/components/PromptCard.tsx
- src/pages/MyPage/components/SalesHistoryCard.tsx
- src/types/MyPage/account.ts
- close #125 
QA 반영하여 UI 수정
결제내역/판매내역/출금가능금액 불로오기 API 연결
> [Feat] 마이페이지 UI 수정 및 결제 관련 API 연결

- src/pages/MyPage/MyMessagePage.tsx
- src/pages/PromptCreatePage/PromptCreatePage.tsx
- src/pages/PromptCreatePage/components/MobileUploadModal.tsx
- src/pages/PromptCreatePage/components/ModelDropdown.tsx
- src/pages/PromptCreatePage/components/PriceDropdown.tsx
- src/pages/PromptCreatePage/components/TagInput.tsx
- src/pages/PromptCreatePage/components/UploadModal.tsx
- src/pages/PromptEdit/PromptEditPage.tsx
- src/pages/PromptEdit/components/MobileUploadModal.tsx
- src/pages/PromptEdit/components/PriceDropdown.tsx
- src/pages/PromptEdit/components/UploadModal.tsx
- src/pages/PromptGuidePage/PromptGuidePage.tsx
- src/pages/PromptGuidePage/components/Pagination.tsx
- close #131 
2번째 QA (QA 시트상에서는 1차 QA 내용) 수정하여 반영했습니다. 
> [Design] QA 2차 수정

- src/pages/MainPage/components/MobilePrompter.tsx
> Fix:메인페이지 팔로우 수정

- src/pages/PromptDetailPage/PromptDetailPage.tsx
- src/pages/PromptDetailPage/components/CreateModal.tsx
- src/pages/PromptDetailPage/components/PromptActions.tsx
- src/pages/PromptDetailPage/components/PromptHeader.tsx
- src/pages/PromptDetailPage/components/PromptInfo.tsx
- src/pages/PromptDetailPage/components/ReviewList.tsx
- src/pages/PromptDetailPage/components/UpdateModal.tsx
- src/utils/reviewUtils.ts
> [Design] qa 수정사항 프롬프트 상세보기

- src/pages/ProfilePage/ProfilePage.tsx
> [Design] 핸드폰 크기 비율 수정

- src/pages/ProfilePage/ProfilePage.tsx
- close #96 
> 구매 이력 있는 경우 삭제되지 않도록 모달 처리 추가함
> [Fix] 구매 이력 있는 경우 삭제되지 않도록 수정

- src/pages/MyPage/components/AccountEditForm.tsx
> [Feat] 계좌정보 등록/조회 api 연결 

- src/pages/MyPage/MyPaymentHistoryPage.tsx
- close #
서비스 워커 자동 생성 테스트 위한 코드 수정
> [Refactor]: 더미데이터 삭제

- src/pages/MyPage/MyAccountPage.tsx
- src/pages/MyPage/MyPayPage.tsx
- src/pages/MyPage/components/PossiblepayAmount.tsx
> [Feat]  출금요청 페이지 계좌정보 연결

- src/pages/MyPage/MyPromptPage.tsx
> 🐛 [Fix] 프롬프트 삭제하기 관련 오류 해결

- src/layouts/ProtectedLayout.tsx
- src/main.tsx
> [Design] 불필요한 alert창 제거

- src/pages/MyPage/MyMessagePage.tsx
- src/pages/MyPage/components/MessagePagination.tsx
- src/pages/MyPage/components/NotificationPagination.tsx
- src/pages/PromptCreatePage/PromptCreatePage.tsx
- src/pages/PromptCreatePage/components/Editer.tsx
- src/pages/PromptCreatePage/components/TagInput.tsx
- src/pages/PromptEdit/PromptEditPage.tsx
- src/pages/PromptEdit/components/TagInput.tsx
> [Fix] QA 3차 수정

- src/pages/PromptDetailPage/components/PromptInfo.tsx
> ✨ [Feat] 미리보기 글 표시 (#88)

- src/pages/PromptCreatePage/PromptCreatePage.tsx
- src/pages/PromptEdit/PromptEditPage.tsx
- src/pages/PromptEdit/components/Editer.tsx
- close #160 
누락된 내용 추가합니다.
수정 페이지 Editor 문제 수정 (overflow 문제)
> [Design ] 수정 페이지 Editor 문제 수정 

- src/pages/MainPage/MainPage.tsx
> [fix] 메인페이지 정렬, 검색 기능 수정

- src/hooks/mutations/ProfilePage/useDeleteInquiries.ts
- src/hooks/queries/ProfilePage/useGetInquiries.ts
- close #96 
> 문의 삭제하기 할 때 바로 적용이 안 되는 문제 해결
> queryKey 수정했습니다.
> [Fix] 문의함 queryKey 수정

- src/components/Navbar.tsx
- src/components/Sidebar.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/types/ProfilePage/profile.ts
> [Feat] 사용자 이미지 연결

- src/pages/MyPage/MyPayPage.tsx
- src/pages/MyPage/MyPaymentHistoryPage.tsx
- src/pages/MyPage/MyPromptPage.tsx
- src/pages/MyPage/MyReviewPage.tsx
> [Feat] 빈 화면 안내문구 관련 수정

- src/pages/PromptDetailPage/components/PaymentModal.tsx
- src/pages/PromptDetailPage/components/PromptActions.tsx
- close #186 
결제페이지 변수 호출 순서 수정
> [Fix] 결제페이지 수정

- src/pages/PromptDetailPage/components/CreateModal.tsx
- src/pages/PromptDetailPage/components/PromptInfo.tsx
- src/pages/PromptDetailPage/components/UpdateModal.tsx
> [Feat] 디테일 qa수정

- src/pages/MainPage/MainPage.tsx
- src/pages/MainPage/components/MobilePrompter.tsx
- src/pages/MainPage/components/promptCard.tsx
- src/pages/MainPage/components/prompterBar.tsx
- src/pages/PromptDetailPage/components/PaymentModal.tsx
- src/types/MainPage/prompt.ts
- src/types/PromptDetailPage/payments.ts
> [Fix] 메인페이지 QA&결제 API

- src/pages/MainPage/components/MobilePrompt.tsx
- src/pages/MainPage/components/MobilePrompter.tsx
- src/pages/PromptDetailPage/components/PromptActions.tsx
> [Fix] 결제 모달 수정

- src/apis/PromptDetailPage/payments.ts
- src/pages/MyPage/MyPromptPage.tsx
- src/pages/MyPage/components/MyPromptsTabs.tsx
- src/pages/PromptDetailPage/components/PaymentModal.tsx
반응형 디자인에서 마이페이지 프롬프트 목록 가로 너비 통일
- close #
> 마이페이지 반응형 디자인 수정(#209)

- src/components/Button/IconButton.tsx
- src/pages/MyPage/MyMessagePage.tsx
- src/pages/MyPage/components/MessagePagination.tsx
- src/pages/MyPage/components/NotificationPagination.tsx
> [Fix] 3.5차 QA 추가 수정 내용 반영

- src/assets/icon-unread.svg
- src/layouts/AdminLayout.tsx
- src/pages/AdminPage/AdiminComplaintPage.tsx
- src/pages/AdminPage/AdminComplaintDetailPage.tsx
- src/pages/AdminPage/ComplaintDetailPage.tsx
- src/pages/AdminPage/assets/arrow-left.svg
- src/pages/AdminPage/assets/arrow-right.svg
- src/pages/AdminPage/components/ComplaintCard.tsx
- src/pages/AdminPage/components/Pagination.tsx
- src/routes/pageRoutes.tsx
- src/routes/routes.tsx
- close #234 
관리자 페이지 UI 구현하였습니다. api연동은 추후 연결 끝나면 Push 할 예정입니다.
> [Feat] 관리자 신고함 페이지 UI구현
